# Generated by Django 5.1.4 on 2025-01-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_Reveiw_Page',
            new_name='Book_Review_Page',
        ),
        migrations.RenameModel(
            old_name='Reveiwer',
            new_name='Reviewer',
        ),
        migrations.RenameModel(
            old_name='Reveiwer_Text',
            new_name='Reviewer_Text',
        ),
        migrations.RenameField(
            model_name='book_review_page',
            old_name='reveiwers',
            new_name='reviewers',
        ),
        migrations.RenameField(
            model_name='reviewer',
            old_name='reveiwer_text',
            new_name='reviewer_texts',
        ),
    ]
