# Generated by Django 5.1.4 on 2025-01-13 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0004_alter_book_review_page_reviewers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_review_page',
            name='reviewers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='book_manager.reviewer'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='reviewer_texts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_text', to='book_manager.reviewer_text'),
        ),
    ]
