# Generated by Django 5.1.4 on 2025-01-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0005_alter_book_review_page_reviewers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_review_page',
            name='reviewers',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='reviewer_texts',
        ),
        migrations.AddField(
            model_name='book_review_page',
            name='reviewers',
            field=models.ManyToManyField(related_name='reviewers', to='book_manager.reviewer'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='reviewer_texts',
            field=models.ManyToManyField(related_name='reviewer_text', to='book_manager.reviewer_text'),
        ),
    ]
