# Generated by Django 5.1.4 on 2025-01-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0006_remove_book_review_page_reviewers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readers',
            name='favorite_books',
        ),
        migrations.AddField(
            model_name='readers',
            name='favorite_books',
            field=models.ManyToManyField(related_name='favorite_books', to='book_manager.reader_favorite_books'),
        ),
    ]
