# Generated by Django 5.1.4 on 2024-12-15 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodcut_name', models.CharField(max_length=255)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('d', 'd')], max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('made_in', models.CharField(choices=[('EG', 'egypt'), ('CHA', 'china')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prod', to='cloth_management.cloth')),
            ],
        ),
    ]
